### ISSUE TITLE
patch 2.0.5

### ISSUE THREAD

**Issue by sebyg666** [H4vC/PoeHud#89]
Cant get hud to stay on top of game window or just wont work since a couple hours ago. Worked fine last night after patch which is why its causing me a headache. tried restranting game, setting game to full screen windowed, windowed, fullscreen. tried restarting pc too. restarted hud many times. redownloaded it too. nothing works so far. Any help would be great, thanks

**Comment by sebyg666** [comment]
update: VMV's version works for me for some reason. im baffelled

**Comment by ghost** [comment]
That's because it's updated. :D 

...https://github.com/smad2005/PoeHud/compare/e954e5f30c...2b99ab8784

**Comment by sebyg666** [comment]
@VMV haha ty, BTW could you make a toggle for weather you want the XP area to be on a toggle with f10 please. i prefer being able to perma it off with f10 then having to hold it. also it doesnt calc DPS correctly. My bow has 322pdps, its calculating it as 315.

**Comment by sebyg666** [comment]
elemental DPS too

**Comment by ghost** [comment]
To switch off perma, you can disable it or change for only area name. F10 is only needed to see items stats and when the screen is filled with shit info. Before the change, there was on option to perma off xph, but if you had dmg and monster kill disabled, they would show up. 
I'm really a novice at codding, and i try to keep up with updated how i can... because i don't see anyone else to do it with the new menu style.
Maybe in the future, someone more experienced will take care of it.
- I will check for the damage calc...can be something wrong after implementing all updates from smad2005...has givven me lots of headakes :D

**Comment by ghost** [comment]
Checked the dmg with both version, new menu - smad2005 ...they are both the same.
Are you sure it's something wrong with calc ?

**Comment by sebyg666** [comment]
my bow pDPS is 143 -335  and 5-95 eDPS and AS is 1.35. its calculating it as 315.2 and 67.2. However 
((143 + 335) / 2 ) x 1.35 = 322.65 
((5 + 95) / 2 ) x 1.35 = 67.5 (it was showing this as 62 earlyer, seems it changes lol )

**Comment by sebyg666** [comment]
![image](https://dl.dropboxusercontent.com/u/12827052/Untitled.png)  

here is a print screen for you

**Comment by sebyg666** [comment]
![image2](https://dl.dropboxusercontent.com/u/12827052/correct%20calc.png) 

this is however calculated correctly. Is it something to do with the master craft mod on the bow?

**Comment by Darktransat** [comment]
i don't know wich Version i had installed 2 days ago, but i figured out, that the DPS-Numbers are without Quality. So this could be the reason, that sebyg's Sword show the correct DPS.
Sry... my english ist not my native language..
